version: 1
author: Fish-Face
language: Haskell
dockerfile: .docker/Dockerfile
#image: haskell
persistence:
  - /code/dist-newstyle/
  - /root/.cache/
  - /root/.local/
code: /code
workdir: /code
runonce: cabal build -O2 day%zeroday%
prerun: ln -s $(cabal list-bin -O2 day%zeroday%) /tmp/cmd
cmd: /tmp/cmd inputs/%zeroday%.txt
daypath: src/%zeroday%.hs
inputfile: inputs/%zeroday%.txt
answerfile: answers/%zeroday%.txt
common:
  - common
